npm = "https://nodejs.org/en/download"
go = "https://go.dev/"
neofetch = "https://github.com/dylanaraps/neofetch/wiki/Installation"
gpg = "https://www.gnupg.org/download/"
stow = "https://www.gnu.org/software/stow/"
docker = "https://www.docker.com/products/docker-desktop/"
deno = "https://deno.com/"
uv = "https://docs.astral.sh/uv/getting-started/installation/"
poetry = "https://python-poetry.org/docs/#installing-with-the-official-installer"
"vscodium(rename from codium)" = "vscodium path variables"
"vscodeinsiders(rename from code-insiders)" = "vscodeinsiders path variable"
"artifacthub(rename from ah)" = "https://artifacthub.io/docs/topics/cli/ - use pre-compiled binary"
"containerdev(rename from cn)" = "https://docs.continue.dev/guides/cli"