set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
unbind C-b
set-option -g prefix C-a
set-option -g repeat-time 0
set-option -g focus-events on
set-window-option -g mode-keys vi
set -g mouse on
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded"
bind o run-shell "open #{pane_current_path}"
unbind a
bind -r a move-window -r \; display "Renumber finished"
bind -r e kill-pane -a
bind -r k select-pane -U 
bind -r j select-pane -D
bind -r l select-pane -R 
unbind %
bind v split-window -h
unbind '"'
bind h split-window -v
unbind &
bind z confirm-before -p "kill-window #P? (y/n)" kill-window

# NOTE: C-S => control-shift
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5
set -g base-index 1
set-option -g status-justify "left"
set-window-option -g mode-keys vi
set-option -g status-fg white
set-option -g status-bg black
set -g pane-active-border-style fg=colour166,bg=default

# important
# control the window text color
set -g window-style fg=colour252,bg=default # font-color: white
set -g window-active-style fg=colour252,bg=default
set-option -g history-limit 64096
set -sg escape-time 10
set-option -g status-style bg=colour235,fg=colour136,default
set-window-option -g window-status-style fg=colour244,bg=colour234,dim
set-window-option -g window-status-current-style fg=colour166,bg=default,bright
set-option -g pane-border-style fg=colour235
set-option -g pane-active-border-style fg=colour136,bg=colour23
set-option -g message-style bg=colour235,fg=colour166
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange
set-window-option -g clock-mode-colour colour64 #green
set -g set-titles on
set -g set-titles-string "#T"
set -g pane-border-status off
set-option -g status-position top
set -g default-shell /opt/homebrew/bin/fish
set -g default-command "/opt/homebrew/bin/fish"

# status line
set -g mode-style "fg=#eee8d5,bg=#07420c"
set -g message-style "bold,fg=#eee8d5,bg=#202020"
set -g message-command-style "fg=#eee8d5,bg=#202020"
set -g pane-border-style "fg=#eee8d5"
set -g pane-active-border-style "fg=#eee8d5"
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-style "fg=#586e75,bg=#073642"
set -g status-bg "#202020"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE

#h = host
set -g status-left "#[fg=#073642,bg=#fddd7a,bold] #S #[fg=#fddd7a,bg=#202020,nobold,nounderscore,noitalics]"
set -g status-right '#[fg=#becbbb,bg=#202020,nobold,nounderscore,noitalics]#[fg=#141715,bg=#becbbb,nobold,nounderscore,noitalics]#[fg=#374549,bg=#141715,nobold,nounderscore,noitalics]\
#[fg=#466559,bg=#374549,nobold,nounderscore,noitalics]#[fg=#60656b,bg=#466559,nobold,nounderscore,noitalics]#[fg=#15161e,bg=#60656b] %a \
#[fg=#657b83,bg=#60656b,nobold,nounderscore,noitalics]#[fg=#252735,bg=#657b83,bold] %d-%m-%Y '
setw -g window-status-activity-style "underscore,fg=#eee8d5,bg=#202020"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#eee8d5,bg=#202020"
# original window-status-format #W#F (window, flag)
setw -g window-status-format '#[fg=#202020,bg=#202020]#[default] #I  #W '
setw -g window-status-current-format '#[fg=#ff5500,bg=#202020]  #I #[fg=#202020,bg=#eee8d5] #[fg=#073642,bg=#eee8d5,bold]#W #[fg=#eee8d5,bg=#202020,nobold]'
if-shell "uname -s | grep -q Darwin" {
  set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
  set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
}
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
run '~/.tmux/plugins/tpm/tpm'